name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up Foundry
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Step 3: Clean up Foundry cache and submodules
      - name: Clean up Foundry and submodules
        run: |
          forge clean
          rm -rf .gitmodules
          rm -rf .git/modules/*
          rm -rf lib
          touch .gitmodules

      # Step 4: Display Forge version (optional)
      - name: Show Forge version
        run: forge --version

      # Step 5: Install dependencies using your Makefile
      - name: Install dependencies
        run: make install

      # Step 6: Format code (optional)
      - name: Run Forge fmt
        run: forge fmt --check

      # Step 7: Build your project
      - name: Build project
        run: make build

      # Step 8: Run tests
      - name: Run tests
        run: make test
